public class trem {
    public static void main(String args[]) {
        System.out.println("___________   ___________________________________________");
        System.out.println(" ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("           |||                    |   |   | |  |  |         \\");
        System.out.println("           |||                    |___|___| |  |__|          )");
        System.out.println("___________|||______________________________|_______________/");
        System.out.println("           |||                                         /--------");
        System.out.println("           |||          juliano  apertado             /-----");
        System.out.println("           |||                                       /---");
        System.out.println("-----------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("____________   ___________________________________________");
        System.out.println("  ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("            |||                    |   |   | |  |  |         \\");
        System.out.println("            |||                    |___|___| |  |__|          )");
        System.out.println("____________|||______________________________|_______________/");
        System.out.println("            |||                                         /--------");
        System.out.println("            |||          juliano  apertado             /-----");
        System.out.println("            |||                                       /---");
        System.out.println("------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_____________   ___________________________________________");
        System.out.println("   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("             |||                    |   |   | |  |  |         \\");
        System.out.println("             |||                    |___|___| |  |__|          )");
        System.out.println("_____________|||______________________________|_______________/");
        System.out.println("             |||                                         /--------");
        System.out.println("             |||          juliano  apertado             /-----");
        System.out.println("             |||                                       /---");
        System.out.println("-------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("______________   ___________________________________________");
        System.out.println("_    ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("_| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("              |||                    |   |   | |  |  |         \\");
        System.out.println("              |||                    |___|___| |  |__|          )");
        System.out.println("______________|||______________________________|_______________/");
        System.out.println("              |||                                         /--------");
        System.out.println("              |||          juliano  apertado             /-----");
        System.out.println("              |||                                       /---");
        System.out.println("--------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_______________   ___________________________________________");
        System.out.println("__   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("  | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("__| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("               |||                    |   |   | |  |  |         \\");
        System.out.println("               |||                    |___|___| |  |__|          )");
        System.out.println("_______________|||______________________________|_______________/");
        System.out.println("               |||                                         /--------");
        System.out.println("               |||          juliano  apertado             /-----");
        System.out.println("               |||                                       /---");
        System.out.println("---------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("________________   ___________________________________________");
        System.out.println("___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                |||                    |   |   | |  |  |         \\");
        System.out.println("                |||                    |___|___| |  |__|          )");
        System.out.println("________________|||______________________________|_______________/");
        System.out.println("                |||                                         /--------");
        System.out.println("                |||          juliano  apertado             /-----");
        System.out.println("                |||                                       /---");
        System.out.println("----------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_________________   ___________________________________________");
        System.out.println(" ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                 |||                    |   |   | |  |  |         \\");
        System.out.println("                 |||                    |___|___| |  |__|          )");
        System.out.println("_________________|||______________________________|_______________/");
        System.out.println("                 |||                                         /--------");
        System.out.println("                 |||          juliano  apertado             /-----");
        System.out.println("                 |||                                       /---");
        System.out.println("-----------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_________________   ___________________________________________");
        System.out.println(" ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                 |||                    |   |   | |  |  |         \\");
        System.out.println("                 |||                    |___|___| |  |__|          )");
        System.out.println("_________________|||______________________________|_______________/");
        System.out.println("                 |||                                         /--------");
        System.out.println("                 |||          juliano  apertado             /-----");
        System.out.println("                 |||                                       /---");
        System.out.println("-----------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("__________________   ___________________________________________");
        System.out.println("  ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                  |||                    |   |   | |  |  |         \\");
        System.out.println("                  |||                    |___|___| |  |__|          )");
        System.out.println("__________________|||______________________________|_______________/");
        System.out.println("                  |||                                         /--------");
        System.out.println("                  |||          juliano  apertado             /-----");
        System.out.println("                  |||                                       /---");
        System.out.println("------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("___________________   ___________________________________________");
        System.out.println("   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                   |||                    |   |   | |  |  |         \\");
        System.out.println("                   |||                    |___|___| |  |__|          )");
        System.out.println("___________________|||______________________________|_______________/");
        System.out.println("                   |||                                         /--------");
        System.out.println("                   |||          juliano  apertado             /-----");
        System.out.println("                   |||                                       /---");
        System.out.println("-------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("____________________   ___________________________________________");
        System.out.println("_   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("_| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                    |||                    |   |   | |  |  |         \\");
        System.out.println("                    |||                    |___|___| |  |__|          )");
        System.out.println("____________________|||______________________________|_______________/");
        System.out.println("                    |||                                         /--------");
        System.out.println("                    |||          juliano  apertado             /-----");
        System.out.println("                    |||                                       /---");
        System.out.println("--------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_____________________   ___________________________________________");
        System.out.println("__   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("  | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("__| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                     |||                    |   |   | |  |  |         \\");
        System.out.println("                     |||                    |___|___| |  |__|          )");
        System.out.println("_____________________|||______________________________|_______________/");
        System.out.println("                     |||                                         /--------");
        System.out.println("                     |||          juliano  apertado             /-----");
        System.out.println("                     |||                                       /---");
        System.out.println("---------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("______________________   ___________________________________________");
        System.out.println("___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                      |||                    |   |   | |  |  |         \\");
        System.out.println("                      |||                    |___|___| |  |__|          )");
        System.out.println("______________________|||______________________________|_______________/");
        System.out.println("                      |||                                         /--------");
        System.out.println("                      |||          juliano  apertado             /-----");
        System.out.println("                      |||                                       /---");
        System.out.println("----------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_______________________   ___________________________________________");
        System.out.println(" ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                       |||                    |   |   | |  |  |         \\");
        System.out.println("                       |||                    |___|___| |  |__|          )");
        System.out.println("_______________________|||______________________________|_______________/");
        System.out.println("                       |||                                         /--------");
        System.out.println("                       |||          juliano  apertado             /-----");
        System.out.println("                       |||                                       /---");
        System.out.println("-----------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("________________________   ___________________________________________");
        System.out.println("  ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                        |||                    |   |   | |  |  |         \\");
        System.out.println("                        |||                    |___|___| |  |__|          )");
        System.out.println("________________________|||______________________________|_______________/");
        System.out.println("                        |||                                         /--------");
        System.out.println("                        |||          juliano  apertado             /-----");
        System.out.println("                        |||                                       /---");
        System.out.println("------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_________________________   ___________________________________________");
        System.out.println("   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                         |||                    |   |   | |  |  |         \\");
        System.out.println("                         |||                    |___|___| |  |__|          )");
        System.out.println("_________________________|||______________________________|_______________/");
        System.out.println("                         |||                                         /--------");
        System.out.println("                         |||          juliano  apertado             /-----");
        System.out.println("                         |||                                       /---");
        System.out.println("-------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("__________________________   ___________________________________________");
        System.out.println("_   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("_| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                          |||                    |   |   | |  |  |         \\");
        System.out.println("                          |||                    |___|___| |  |__|          )");
        System.out.println("__________________________|||______________________________|_______________/");
        System.out.println("                          |||                                         /--------");
        System.out.println("                          |||          juliano  apertado             /-----");
        System.out.println("                          |||                                       /---");
        System.out.println("--------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("___________________________   ___________________________________________");
        System.out.println("__   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("  | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("__| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                           |||                    |   |   | |  |  |         \\");
        System.out.println("                           |||                    |___|___| |  |__|          )");
        System.out.println("___________________________|||______________________________|_______________/");
        System.out.println("                           |||                                         /--------");
        System.out.println("                           |||          juliano  apertado             /-----");
        System.out.println("                           |||                                       /---");
        System.out.println("---------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("____________________________   ___________________________________________");
        System.out.println("___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                            |||                    |   |   | |  |  |         \\");
        System.out.println("                            |||                    |___|___| |  |__|          )");
        System.out.println("____________________________|||______________________________|_______________/");
        System.out.println("                            |||                                         /--------");
        System.out.println("                            |||          juliano  apertado             /-----");
        System.out.println("                            |||                                       /---");
        System.out.println("----------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_____________________________   ___________________________________________");
        System.out.println(" ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                             |||                    |   |   | |  |  |         \\");
        System.out.println("                             |||                    |___|___| |  |__|          )");
        System.out.println("_____________________________|||______________________________|_______________/");
        System.out.println("                             |||                                         /--------");
        System.out.println("                             |||          juliano  apertado             /-----");
        System.out.println("                             |||                                       /---");
        System.out.println("-----------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("______________________________   ___________________________________________");
        System.out.println("  ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                              |||                    |   |   | |  |  |         \\");
        System.out.println("                              |||                    |___|___| |  |__|          )");
        System.out.println("______________________________|||______________________________|_______________/");
        System.out.println("                              |||                                         /--------");
        System.out.println("                              |||          juliano  apertado             /-----");
        System.out.println("                              |||                                       /---");
        System.out.println("------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_______________________________   ___________________________________________");
        System.out.println("   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                               |||                    |   |   | |  |  |         \\");
        System.out.println("                               |||                    |___|___| |  |__|          )");
        System.out.println("_______________________________|||______________________________|_______________/");
        System.out.println("                               |||                                         /--------");
        System.out.println("                               |||          juliano  apertado             /-----");
        System.out.println("                               |||                                       /---");
        System.out.println("-------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("________________________________   ___________________________________________");
        System.out.println("_   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("_| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                |||                    |   |   | |  |  |         \\");
        System.out.println("                                |||                    |___|___| |  |__|          )");
        System.out.println("________________________________|||______________________________|_______________/");
        System.out.println("                                |||                                         /--------");
        System.out.println("                                |||          juliano  apertado             /-----");
        System.out.println("                                |||                                       /---");
        System.out.println("--------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_________________________________   ___________________________________________");
        System.out.println("__   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("  | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("__| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                 |||                    |   |   | |  |  |         \\");
        System.out.println("                                 |||                    |___|___| |  |__|          )");
        System.out.println("_________________________________|||______________________________|_______________/");
        System.out.println("                                 |||                                         /--------");
        System.out.println("                                 |||          juliano  apertado             /-----");
        System.out.println("                                 |||                                       /---");
        System.out.println("---------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("__________________________________   ___________________________________________");
        System.out.println("___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                  |||                    |   |   | |  |  |         \\");
        System.out.println("                                  |||                    |___|___| |  |__|          )");
        System.out.println("__________________________________|||______________________________|_______________/");
        System.out.println("                                  |||                                         /--------");
        System.out.println("                                  |||          juliano  apertado             /-----");
        System.out.println("                                  |||                                       /---");
        System.out.println("----------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("___________________________________   ___________________________________________");
        System.out.println(" ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                   |||                    |   |   | |  |  |         \\");
        System.out.println("                                   |||                    |___|___| |  |__|          )");
        System.out.println("___________________________________|||______________________________|_______________/");
        System.out.println("                                   |||                                         /--------");
        System.out.println("                                   |||          juliano  apertado             /-----");
        System.out.println("                                   |||                                       /---");
        System.out.println("-----------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("____________________________________   ___________________________________________");
        System.out.println("  ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                    |||                    |   |   | |  |  |         \\");
        System.out.println("                                    |||                    |___|___| |  |__|          )");
        System.out.println("____________________________________|||______________________________|_______________/");
        System.out.println("                                    |||                                         /--------");
        System.out.println("                                    |||          juliano  apertado             /-----");
        System.out.println("                                    |||                                       /---");
        System.out.println("------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_____________________________________   ___________________________________________");
        System.out.println("   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                     |||                    |   |   | |  |  |         \\");
        System.out.println("                                     |||                    |___|___| |  |__|          )");
        System.out.println("_____________________________________|||______________________________|_______________/");
        System.out.println("                                     |||                                         /--------");
        System.out.println("                                     |||          juliano  apertado             /-----");
        System.out.println("                                     |||                                       /---");
        System.out.println("-------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("______________________________________   ___________________________________________");
        System.out.println("_   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("_| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                      |||                    |   |   | |  |  |         \\");
        System.out.println("                                      |||                    |___|___| |  |__|          )");
        System.out.println("______________________________________|||______________________________|_______________/");
        System.out.println("                                      |||                                         /-------");
        System.out.println("                                      |||          juliano  apertado             /-----");
        System.out.println("                                      |||                                       /---");
        System.out.println("--------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_______________________________________   ___________________________________________");
        System.out.println("__   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("  | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("__| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                       |||                    |   |   | |  |  |         \\");
        System.out.println("                                       |||                    |___|___| |  |__|          )");
        System.out.println("_______________________________________|||______________________________|_______________/");
        System.out.println("                                       |||                                         /-------");
        System.out.println("                                       |||          juliano  apertado             /-----");
        System.out.println("                                       |||                                       /---");
        System.out.println("---------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("________________________________________   ___________________________________________");
        System.out.println("___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                        |||                    |   |   | |  |  |         \\");
        System.out.println("                                        |||                    |___|___| |  |__|          )");
        System.out.println("________________________________________|||______________________________|_______________/");
        System.out.println("                                        |||                                         /------");
        System.out.println("                                        |||          juliano  apertado             /-----");
        System.out.println("                                        |||                                       /---");
        System.out.println("----------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_________________________________________   ___________________________________________");
        System.out.println(" ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                         |||                    |   |   | |  |  |         \\");
        System.out.println("                                         |||                    |___|___| |  |__|          )");
        System.out.println("_________________________________________|||______________________________|_______________/");
        System.out.println("                                         |||                                         /-----");
        System.out.println("                                         |||          juliano  apertado             /-----");
        System.out.println("                                         |||                                       /---");
        System.out.println("-----------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("__________________________________________   ___________________________________________");
        System.out.println("  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println(" |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println(" |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("                                          |||                    |   |   | |  |  |         \\");
        System.out.println("                                          |||                    |___|___| |  |__|          ");
        System.out.println("__________________________________________|||______________________________|_______________/");
        System.out.println("                                          |||                                         /----");
        System.out.println("                                          |||          juliano  apertado             /-----");
        System.out.println("                                          |||                                       /---");
        System.out.println("------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println(" __________________________________________   ___________________________________________");
        System.out.println("|  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        \\");
        System.out.println("|                                          |||                    |   |   | |  |  |         ");
        System.out.println("|                                          |||                    |___|___| |  |__|         ");
        System.out.println("|__________________________________________|||______________________________|_______________");
        System.out.println("|                                          |||                                         /----");
        System.out.println("|                                          |||          juliano  apertado             /-----");
        System.out.println("|                                          |||                                       /---");
        System.out.println("'------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("  __________________________________________   ___________________________________________");
        System.out.println("||  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("|| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____\\");
        System.out.println("|| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |        ");
        System.out.println("||                                          |||                    |   |   | |  |  |        ");
        System.out.println("||                                          |||                    |___|___| |  |__|        ");
        System.out.println("||__________________________________________|||______________________________|______________");
        System.out.println("||                                          |||                                         /---");
        System.out.println("||                                          |||          juliano  apertado             /----");
        System.out.println("||                                          |||                                       /---");
        System.out.println("''------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("   __________________________________________   ___________________________________________");
        System.out.println("|||  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----\\");
        System.out.println("||| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |_____");
        System.out.println("||| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |       ");
        System.out.println("|||                                          |||                    |   |   | |  |  |       ");
        System.out.println("|||                                          |||                    |___|___| |  |__|       ");
        System.out.println("|||__________________________________________|||______________________________|_____________");
        System.out.println("|||                                          |||                                         /--");
        System.out.println("|||                                          |||          juliano  apertado             /---");
        System.out.println("|||                                          |||                                       /---");
        System.out.println("'''------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("_   __________________________________________   ___________________________________________");
        System.out.println(" |||  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,----");
        System.out.println("|||| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |____");
        System.out.println("|||| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |      ");
        System.out.println(" |||                                          |||                    |   |   | |  |  |      ");
        System.out.println(" |||                                          |||                    |___|___| |  |__|      ");
        System.out.println("_|||__________________________________________|||______________________________|____________");
        System.out.println(" |||                                          |||                                         /-");
        System.out.println(" |||                                          |||          juliano  apertado             /--");
        System.out.println(" |||                                          |||                                       /---");
        System.out.println("-'''------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("__   __________________________________________   __________________________________________");
        System.out.println("_ |||  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,---");
        System.out.println(" |||| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |___");
        System.out.println("_|||| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |     ");
        System.out.println("  |||                                          |||                    |   |   | |  |  |     ");
        System.out.println("  |||                                          |||                    |___|___| |  |__|     ");
        System.out.println("__|||__________________________________________|||______________________________|___________");
        System.out.println("  |||                                          |||                                         /");
        System.out.println("  |||                                          |||          juliano  apertado             /-");
        System.out.println("  |||                                          |||                                       /--");
        System.out.println("--'''------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("___   __________________________________________   _________________________________________");
        System.out.println("__ |||  ___   ___   ___   ___   ___   ___   ___ |||  ___   ___   ___    ___ ___  |   __  ,--");
        System.out.println("  |||| |   | |   | |   | |   | |   | |   | |   |||| |   | |   | |   |  |   |   | |  |  | |__");
        System.out.println("__|||| |___| |___| |___| |___| |___| |___| |___|||| |___| |___| |___|  | O | O | |  |  |    ");
        System.out.println("   |||                                          |||                    |   |   | |  |  |    ");
        System.out.println("   |||                                          |||                    |___|___| |  |__|    ");
        System.out.println("___|||__________________________________________|||______________________________|__________");
        System.out.println("   |||                                          |||                                         ");
        System.out.println("   |||                                          |||          juliano  apertado             /");
        System.out.println("   |||                                          |||                                       /-");
        System.out.println("---'''------------------------------------------'''---------------------------------------'");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
    }
}

// head
[
    " ___________________________________________",
    "|  ___   ___   ___    ___ ___  |   __  ,----\\",
    "| |   | |   | |   |  |   |   | |  |  | |_____\\",
    "| |___| |___| |___|  | O | O | |  |  |        \\",
    "|                    |   |   | |  |  |         \\",
    "|                    |___|___| |  |__|          )",
    "|______________________________|_______________/",
    "|                                         /-------",
    "|          juliano  apertado             /-----",
    "|                                       /---",
    "'---------------------------------------'",
]